Layout/DotPosition:
  Enabled:            false

Layout/ExtraSpacing:
  Enabled:            false

Layout/HeredocIndentation:
  Enabled:            false

Lint/EmptyFile:
  Exclude:
    - 'spec/rails-2-test/config.ru'
    - 'spec/rails-3-test/config.ru'
    - 'spec/rails-4-test/config.ru'

Performance/RegexpMatch:
  Enabled:            false

Style/ConstantVisibility:
  Enabled:            false

Style/HashTransformValues:
  Enabled:            false

Style/InlineComment:
  Enabled:            false

Style/StringConcatenation:
  Enabled:            false

Style/SymbolArray:
  EnforcedStyle:      'brackets'

Style/OptionHash:
  Enabled:            false

Security/YAMLLoad:
  Enabled:            false
